{
  "comments": [
    {
      "key": {
        "uuid": "4e1dcb5b_2e21bb9a",
        "filename": "lib/includes/DataTypeMismatchException.php",
        "patchSetId": 3
      },
      "lineNbr": 0,
      "author": {
        "id": 128
      },
      "writtenOn": "2014-05-22T13:59:24Z",
      "side": 0,
      "message": "huh, why didn\u0027t I see the existing exception? I\u0027ll fix that in the original patch.",
      "revId": "8a281fb5d17370bbb837f7f2feb2c8533dd2a086",
      "serverId": "e9e9afe9-4712-486d-8885-f54b72dd1951",
      "unresolved": false
    }
  ]
}