{
  "comments": [
    {
      "key": {
        "uuid": "9d176fe0_25518a3e",
        "filename": "lib/includes/Store/EntityContentDataCodec.php",
        "patchSetId": 19
      },
      "lineNbr": 163,
      "author": {
        "id": 6708
      },
      "writtenOn": "2019-04-29T14:13:02Z",
      "side": 1,
      "message": "Removed logging, but left the new exception because its name is pretty descriptive.\n\nHowever, bringing the check out of the try/catch block breaks a bunch of tests for Wikibase\\Lib\\Store :/",
      "range": {
        "startLine": 163,
        "startChar": 3,
        "endLine": 163,
        "endChar": 44
      },
      "revId": "b2418360a3f954cfeb25366d811a5a5b138be6f9",
      "serverId": "e9e9afe9-4712-486d-8885-f54b72dd1951",
      "unresolved": true
    }
  ]
}